// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxx',
    appId: '1:855297320127:web:a1a0cee9a7c9451735920a',
    messagingSenderId: '855297320127',
    projectId: 'plot-pixgrid',
    authDomain: 'plot-pixgrid.firebaseapp.com',
    storageBucket: 'plot-pixgrid.appspot.com',
    measurementId: 'G-KZ7PW6LDSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxx',
    appId: '1:855297320127:android:91e0c28224a207a935920a',
    messagingSenderId: '855297320127',
    projectId: 'plot-pixgrid',
    storageBucket: 'plot-pixgrid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:855297320127:ios:2b57c0a6f43faa7c35920a',
    messagingSenderId: '855297320127',
    projectId: 'plot-pixgrid',
    storageBucket: 'plot-pixgrid.appspot.com',
    iosClientId: '855297320127-oqdb93iqe63t53e4rv991e7koec6fb79.apps.googleusercontent.com',
    iosBundleId: 'com.pixgrid.plot',
  );
}
